### ISSUE TITLE
Inverter models

### ISSUE THREAD

**Issue by hakanergun** [sanderclaeys/pmd-data-model#22]
My suggestion would be to have a separate inverter model which can connect "DC" sources such as PV and batteries with the AC grid, rather than having the inverters as part of the PV or storage systems. This would help to avoid having inverters double (thus double the losses), if one would like to connect PV and batteries on the DC side. That would also help to connect many other items interchangeably, I think.

**Comment by sanderclaeys** [comment]
We at some point discussed separating the inverter from the DC source, but at that time decided against it because these user would have to look in two places (whilst in most use cases, each DC-source has its own inverter).

Perhaps a solution can be to allow DC sources to refer to an inverter, or define it in place. When devices refer to an inverter, that inverter lumps all of the devices that refer to it on its DC side.
 
@pseudocubic @frederikgeth thoughts?

**Comment by pseudocubic** [comment]
This is a use case I hadn't considered. I definitely can see the benefit of having multiple DC sources behind a single inverter. 

Like Sander suggested, we could build something in that could lump the inverters together into a single loss model, similar to how the `"bank"` property works on transformers in OpenDSS. I think this would be the most straightforward to add (without having to define an explicit inverter component object).

**Comment by sanderclaeys** [comment]
What I had in mind was more like a `branch/linecode` if we want to support both use cases; either you define the inverter on the component, or you refer to the inverter it connects to. (the difference is that a `linecode`is just a technology, whilst the `inverter` would be a component)

**Comment by ccoffrin** [comment]
If you are going to support DC buses explicitly then I think having a separate inverter component is required and this use case can be supported.  AC components connect to AC buses (which may include a lumped inverter); DC components connect to DC buses; the inverter component links AC and DC buses.

If you not yet plan to support explicit DC buses then, I would say that @hakanergun's proposed use case is out of scope of the current format.

**Comment by akbarnes** [comment]
If we are deferring support of DC components until a later release (which seems reasonable) the use case @hakanergun mentioned could be handled by adding support for dc-linked storage (and possibly loads) to the PV object, or to create a new PV+storage object. There are real inverters designed like this so there is some justification to represent PV+storage as a single object. This would require some extra variables for flow between the pv panels & dc-bus, dc-bus & battery and dc-bus & ac bus.

**Comment by hakanergun** [comment]
hi, in fact we are working on  a multi-conductor DC grid formulation as an extension of PowerModelsACDC.jl. The idea there is also to leverage the multi-conductor support of PMD, and I'd like it to be able to work for both balanced single conductor representation of the AC system as  (PM) well as the multi-conductor version (PMD). We have been focussing on the mathematical derivation so far, and are waiting for the completion of the PMD data model to start implementation.

**Comment by akbarnes** [comment]
Maybe it might make sense to keep a PV + storage object out of PMD + the main data model if a mixed ac-dc formulation is coming. Where would be an appropriate place for a PV + storage object if it does in a different repo, maybe a *Annex.jl repo?
