### ISSUE TITLE
:state in switches maybe confusing?

### ISSUE THREAD

**Issue by MartaVanin** [sanderclaeys/pmd-data-model#23]
Hello,
first of all, I would like to say that I find the engineering data model very well documented, thank you for this.
In switches you have both :state and :status, which are very similar terms. Couldn't this maybe give rise to conclusions? 
I don't know what a good term to replace :state could be, maybe something like :open?

**Comment by sanderclaeys** [comment]
If it was named `open`, there would be no confusion what `open=true` means, whilst `state=true/1` is also more ambiguous. Though instead of `open` I would opt for `closed`, because then the conducting/on state would be `closed=true/1`.

@ccoffrin what is your opinion?

**Comment by pseudocubic** [comment]
we also played with using `String` values `"open"` and `"closed"` for state to make it less confusing, would that be preferable?

**Comment by MartaVanin** [comment]
@pseudocubic I am not sure.. if the switch state is just to be used as input, then I think the string is the clearest, but if you want it to be a variable it is more consistent to just have it already in 1/0, I guess.
I liked sander's :closed suggestion

**Comment by sanderclaeys** [comment]
One idea of the `eng/math` separation is that at the engineering level, we can be more verbose and descriptive, whilst at the mathematical level, it can be closer to what the variables would look like. At the mathematical level, we can assume we are dealing developers, and expect them to know the difference between `state/status`

**Comment by MartaVanin** [comment]
@sanderclaeys then maybe with this approach in mind I find an "open/closed" string more user-friendly

**Comment by ccoffrin** [comment]
In the engineering model I think the eccodings "state" = 0/1 or  "state"="open"/"closed" or "closed" = true/false are all resonable.

In the mathematical model, I would stick with 0/1 values but I would consider changing "state" to "closed", if that is what the final concenus is here.

**Comment by frederikgeth** [comment]
I prefer this option: "state"="open"/"closed"

I note though, that a field `dispatchable` is missing.

**Comment by akbarnes** [comment]
I think having a 0/1 field `closed` is most convenient, I don't see any flexibility gains from using a string value unless you want to include values like "fixed-closed," "fixed-open" or "switchable," but I'd prefer a separate boolean like `dispatchable` or `switchable `for that

**Comment by pseudocubic** [comment]
As @sanderclaeys suggested in #26, it might be better to use `enum` for this, so that 0/1 are acceptable as are enums `OPEN` and `CLOSED`

**Comment by pseudocubic** [comment]
will convert state to enum OPEN and CLOSED
