### ISSUE TITLE
multinetwork and time_series

### ISSUE THREAD

**Issue by MartaVanin** [sanderclaeys/pmd-data-model#24]
Maybe this piece of documentation is not the right place to address this question, but I was wondering how to write multiperiod problems using the new "time_series" entries. Previously, I was using the "multinetwork" paradigm, which required to copy the fixed network data for all the considered time steps. I find it very convenient if that is no longer necessary, as the time_series key seems to suggest.
In any case, will there still be a "multinetwork" => true/false somewhere in the data dictionary or
are multinw calculation automatically enforced when I have time_series in my data? 
Could it be interesting to have the option to explicitly choose one time stamp from the time_series and fall back to single network calculations? 
Please ignore this if this is all information that will appear somewhere at a later stage.

**Comment by sanderclaeys** [comment]
The idea is that starting from the PMD `0.9` release, there will be two data models,
- the engineering data model (`data_eng`), as described here
- the mathematical data model (`data_math`), which is the one we use now

The philosophy is that the engineering data model is more flexible, and more intuitive to users; all units are in SI, there are more components, you can add timeseries the way you described above etc.

Once you assemble your data model as such, you can 'transform' `data_eng` to the mathematical one, which will have a limited set of strictly defined components, and will have the multinetwork structures that you refer to. So in this transformation step, we have added code that will automatically build the multinetwork structure from the time series you defined.

**Comment by MartaVanin** [comment]
ok, I see. So in the data_math it falls back to the old "nw" dictionary structure. 
Say I have two loads but only one of them refers to a time_series. Do you throw an error/warning or do you automatically generate a (constant) time_series for the second load? I can see problems arising if the users overlook their data, so I would throw a very explicit warning

**Comment by sanderclaeys** [comment]
Properties that do not have an associated timeseries, are kept constant. To give a warning when this happens would be difficult, because you can define timeseries on almost any property, not just the `pd_nom/qd_nom` of a load (think of inverter efficiencies, PV irradiances...). So this would generate a lot of warnings in most use cases

**Comment by ccoffrin** [comment]
An orthogonal remark to the `eng` vs `math` modeling discussion.  For general information, Multinetworks are more general than time series.  However, all infrastructure models packages now have some basic support for encoding `time_series` data and helper functions for converting into multinetwork data for the purpose of solving multi-period optimization problems.

https://github.com/lanl-ansi/InfrastructureModels.jl/blob/master/src/core/data.jl#L75
https://github.com/lanl-ansi/InfrastructureModels.jl/blob/master/src/core/data.jl#L117

**Comment by MartaVanin** [comment]
ok, fair enough :)

**Comment by pseudocubic** [comment]
We will with clarifications, but nothing needs to be changed in the model at this time

**Comment by pseudocubic** [comment]
I went back through this and it seems like every question you had @MartaVanin was covered. If not, let us know
