### ISSUE TITLE
v_var_scalar

### ISSUE THREAD

**Issue by MartaVanin** [sanderclaeys/pmd-data-model#25]
I personally find the use of this setting difficult to understand from the present documentation.
Could you perhaps shed some light?

**Comment by sanderclaeys** [comment]
The parameter controls the unit for all voltage and power values, e.g.
- If `v_var_scalar=1`, then all voltages are in `V` and all power in `W` etc 
- If `v_var_scalar=1E3`, then all voltages are in `kV` and all power in `kW` etc

The idea here was to support that some people prefer using `kV` as a unit, other `V` etc. Does this fit your use case, or do you have a better name perhaps?

**Comment by MartaVanin** [comment]
It doesn't particularly matter for my use case, I was just thinking whether it isn't confusing to use the same multiplier for power and volts. Also the name starting with "v_"  suggests it is for voltage, it is a bit puzzling to see it applied to both voltage and power. Maybe a more neutral name like "prescaler" can obviate this problem.
Is there any particular reason for not having two different prescalers for power and voltage instead of one? Because for instance in the low voltage I find it more natural to use volts for voltage and kW for power, given the orders of magnitude in these networks.

**Comment by sanderclaeys** [comment]
I agree that it is confusing, splittting them would be better. (the `_var_` in the name stands for volt ampere reactive)

**Comment by ccoffrin** [comment]
Why not "voltage_scalar"?

**Comment by pseudocubic** [comment]
Having separate power and voltage scalars as @MartaVanin suggests would be fine with me, and we could use names like @ccoffrin's suggestion, `power_scalar`, `voltage_scalar`

**Comment by akbarnes** [comment]
I also vote for separate `power_scaling` and `voltage_ scaling`, as volt-var control is a thing and the existing name invites confusion. Also using `scaling` or `scaling_factor` makes more sense to me than scalar, at least based on my understanding of the word "scalar"

**Comment by ccoffrin** [comment]
something like `voltage_scale_factor` and `power_scale_factor` would be consistent with the naming convention we adopted in power models.

**Comment by pseudocubic** [comment]
will change to `voltage_scale_factor` `power_scale_factor`
