### ISSUE TITLE
model identification

### ISSUE THREAD

**Issue by pseudocubic** [sanderclaeys/pmd-data-model#26]
One comment I received by email suggested that we consider a boolean or enum to identify the model. I put two examples of possibilities for this:

`"data_model" => 1`, indicating e.g. the engineering model, and `2` the mathematical (or some other variant of this)

or something like

`"eng_data_model" => true`.

Thoughts?

**Comment by pseudocubic** [comment]
I misunderstood the point about using an enum. The below would define an enum

```julia
@enum DataModelType ENGINEERING MATHEMATICAL DSS
```

This has the advantage of looking like MathOptInterface while still being human readable.

**Comment by ccoffrin** [comment]
In PowerModels we have avoided enums in the data model in favor of being serializable to native JSON.  So I think that is a feature worth consideration.  If PMD already needs some extra processing (e.g. for multi-conductor values) then I think it is reasonable to also have enums in the data model.

**Comment by sanderclaeys** [comment]
I agree that the timing might be right for enums. Though if we do it here, I would like to do it consistently and add it also in a few other places;
| component | field | enums |
| - | - | - |
| `switch` | `state` | `OPEN`, `CLOSED` |
| many | `configuration` | `WYE`, `DELTA` |
| root | `data_model` | `ENGINEERING`, `MATHEMATICAL` |

Any other ones that you can think of? @pseudocubic @frederikgeth

**Comment by ccoffrin** [comment]
@sanderclaeys, can you confirm if the current JSON serialization of this data format already requires some extra processing?  If not, I don't think enum's along a good reason to add that extra complexity.

FWIW, I have only every suggested the use of enums a codebase, not in a data model.

**Comment by sanderclaeys** [comment]
@ccoffrin Yes, I customized the JSON serialization for Matrix types in the past. This is not good for sharing the model across environments, but made its json output more readable.

Right, though where a property is restricted to a list of strings in the data model, this would be implemented as an enum in the codebase?

**Comment by pseudocubic** [comment]
I have an example of this working in the current data model branch with not many changes having to have been made. I used the JSON serialization framework that we already had that Sander referred to to test this out and it seems to work well

**Comment by ccoffrin** [comment]
BTW, if you are going to start using enums, you probably want to make things consistent throughout.  For example `status` could be an enum.  This might be a slippery slope.

**Comment by pseudocubic** [comment]
It definitely is, I played with this a bit today on an experimental branch and there turns out to be a lot of places in the code where we have to be careful about having everything consistent. That said once I added one (load models) the rest seemed to follow more naturally.

**Comment by ccoffrin** [comment]
"control_mode" was another one that could be turned into an enum

**Comment by pseudocubic** [comment]
Yeah, I tried that one in my experimental branch but I embarrassingly didn’t even think to convert `status` to enumerate

**Comment by pseudocubic** [comment]
we will change to enums `ENGINEERING`, `MATHEMATICAL`, `DSS`
