### ISSUE TITLE
list of people to ask for feedback next?

### ISSUE THREAD

**Issue by frederikgeth** [sanderclaeys/pmd-data-model#27]
- Nando Ochoa
- Andrew Urquhart
- Ray Zimmerman
- Andrew Keane
- Valentin Rigoni
- Roger Dugan
- Tom Short
- Tarek Elgindy
- Bryan Palmintier
- Dheepak Krishnamurthy
- CSIRO colleagues (John, Gavin, Julio, James, Thomas)

**Comment by ccoffrin** [comment]
I would caution about seeking a lot of feedback.  My experience is that there are diminishing returns as more folks are asked.

At this stage, I would focus on getting buy in from any would be near term users.  And after the model has broader adoption, then consider inquiring with a wider collection of folks.
