### ISSUE TITLE
Data structure won't serialize/deserialize to json

### ISSUE THREAD

**Issue by akbarnes** [sanderclaeys/pmd-data-model#28]
JSON only supports string keys. Using arbitrary immutable values as keys for components means that the json encoder will either throw an error or convert the immutable key to a string representation.

**Comment by pseudocubic** [comment]
I'm not sure that all models necessarily need to be straight JSON serializable, just the most common use cases. We could always throw a warning about exports if a user chooses to use a non-string component id, and as you say, those ids will just be converted to strings, so its not like the models will be invalid on re-importation

**Comment by ccoffrin** [comment]
@akbarnes, I'll point you to this discussion, https://github.com/sanderclaeys/pmd-data-model/issues/26.

One of the challenges we have in distribution models is that several parameters are best represented as matricies and JSON does not natively support them.  The current thinking is that we should add a little bit of post processing to convert a JSON encoding into a native matrix.  Once you cross that line, you might as well do other types of transformations (like string values to ENUM values).  This choice is still up for discussion if you have a strong feeling / alternative / use case for a different approach.
