### ISSUE TITLE
Support for aggregations

### ISSUE THREAD

**Issue by akbarnes** [sanderclaeys/pmd-data-model#30]
Currently data model doesn't include aggegrations other than voltage class. Including a circuit field under loads is useful to group loads that must be shed collectively. An aggregation for lines is useful to group lines in planning problems where all lines in a group are hardened collectively.

**Comment by pseudocubic** [comment]
To make sure I understand, you would like to have a standard way to group components (like specifying a zone?), but you don't need an additional Zone data object to keep track of additional information about that zone?

**Comment by akbarnes** [comment]
If zones are supported under PMD then that should work. A potential gotcha is whether branch objects can be associated with a zone, not just their buses.

**Comment by ccoffrin** [comment]
@akbarnes can you elaborate a bit about use cases in distribution networks where groupings like zones/areas/owners are useful?

**Comment by pseudocubic** [comment]
Not needed in the short term, up for discussion later
