### ISSUE TITLE
Generator reactances

### ISSUE THREAD

**Issue by akbarnes** [sanderclaeys/pmd-data-model#32]
I recall an earlier discussion on including a series impedance and possibly GSU as part of the engineering generator model. Explicitly including these in the mathematical representation is convenient for fault modeling. Is this no longer planned?

**Comment by pseudocubic** [comment]
It is not planned in the immediate release, but the fields that would represent that are additive, and should not be breaking changes to the model we have proposed here

**Comment by pseudocubic** [comment]
this would be an additive non-breaking change and we can address in a future release
