### ISSUE TITLE
Fault objects

### ISSUE THREAD

**Issue by akbarnes** [sanderclaeys/pmd-data-model#33]
Another special case of shunt objects. Typically this only includes a bs matrix, though some software also supports gs.

**Comment by pseudocubic** [comment]
This object is additive and therefore can be added in v0.9.1 e.g. and I don't think should hold back the finalization of the current state of the proposed model

**Comment by ccoffrin** [comment]
I might mark this a high priority for v0.9.1 given the near-term use cases.
