### ISSUE TITLE
generalize time series

### ISSUE THREAD

**Issue by akbarnes** [sanderclaeys/pmd-data-model#34]
It sounds like the time_series objects are a convenient way to populate the varying parameters in a multinetwork model? Is it reasonable to generalize them beyond time series? I can think of a couple use cases that can come up:

1. Peak, shoulder & off-peak loadings. This has come up with contingency analysis a couple times. Some decision variables can be shared across loadings even if there are no constraints linking time steps (eg. generator ramping, storage state)
2. Harmonic load flow. Line reactances, transformer reactances and loads will scale depending on the harmonic
3. Periodic time series: Important for considering the operation of storage under nominal conditions
4. contingency scenarios: branch statuses will be 0 or 1 depending on the scenario

**Comment by ccoffrin** [comment]
Are you familiar with the multi-network feature at the mathematical model level?  This can be used to address all of these cases.  I am not immediately seeing a way to make generalized support tools for these specific cases.  Time series has been the one consistent and common structure that we have been able to support with generic helper functions.

**Comment by pseudocubic** [comment]
Seems difficult to support in a general way, recommend to use standard multinetwork support for now
