### ISSUE TITLE
handling control objects

### ISSUE THREAD

**Issue by bluejuniper** [sanderclaeys/pmd-data-model#35]
In OpenDSS, fuses and other protective devices are represented as control objects that point to a terminal of a line or transformer object. In the proposed engineering model, protective devices are a type of edge object. There are 2 issues I can see with this:

1. While representing reclosers or fuses as branches works, some protective relaying schemes such as line pilot protection or differential protection are associated with a whole line or transformer and the protective-device-as-branch approach breaks down.
2. Creating a fuse branch from a fuse control object in an opendss input file will introduce new buses into the engineering model which makes it harder to compare against the original input

**Comment by pseudocubic** [comment]
Do you have a concrete example of a dss circuit definition that uses fuses so I can see how they are typically implemented? 

I didn't appreciate before that fuses could be applied to any terminal of any circuit element. This poses some problems with the current idea that we would have a separate fuse object that is a physical edge. Instead this would make fuses something like a data object and any object could refer to an object in the fuse table. 

Can you give me an example of how you would plan to use the fuse object when its on an arbitrary object?

**Comment by bluejuniper** [comment]
OpenDSS does include a DG case with fuses under the IEEE test cases:
https://sourceforge.net/p/electricdss/code/HEAD/tree/trunk/Distrib/IEEETestCases/DG_Protection/DG_Prot_Fdr.dss

Common examples of where fuses would go would be on the "from" bus of a lateral line in a distribution system where it connects to the feeder trunk, or the primary terminal of a distribution transformer.

**Comment by pseudocubic** [comment]
We don't think this will be used in the near term in OPF or MLD problems, so we will convert fuses to a data object and revisit it in future versions
