### ISSUE TITLE
DSS Data Model

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#36]
What does "data_model" => "dss" mean?

**Comment by pseudocubic** [comment]
It is raw dss, the reason to keep track of this is for a node counting tool we have, where it needs to know what data type it has in order to accurately count active nodes in the network

**Comment by ccoffrin** [comment]
Is it an internal model?  If so maybe we don't need to document its existence here?

**Comment by pseudocubic** [comment]
`parse_dss` is a public function, I personally think it is useful to be able to get the pure dss data in an obvious way, I use it a lot for ensuring consistency between the different models
