### ISSUE TITLE
Types of Values for Connections, Terminals, Phases, ...

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#37]
Are they really `Vector{Any}`?  Seems super hard to do correctness checking on this.  For example `[1.2, "c", 3, "n"]` would be a valid input.  If possible, I would strengthen most of the "Any" types to "String", I think that is sufficiently general.

**Comment by pseudocubic** [comment]
We have gone back and forth on this, and the original use case was that we wanted to support people specifying phases like “a”, “b”, “c”, etc, but we only implemented integers, and frankly it would be more convenient to stick only with ints. Thoughts @sanderclaeys ?

**Comment by ccoffrin** [comment]
Personally I like Ints ids, but I can see the convenience of String ids at the engineering level.  I think the risks of Any over String do not outweigh the possible benefits; but I am willing to be convinced otherwise.

**Comment by sanderclaeys** [comment]
The solution dictionary will contain dicts which are indexed over the terminals, which currently get converted to strings when being retrieved; also serialization will be easier if they have to be strings. Perhaps sticking to `String` will make our life easier?

@ccoffrin Do you think converting to Ints is important speed-wise? In terms of faster lookups, these Dicts always contain 4 pairs tops, so perhaps this is different than for component dicts with many pairs?

**Comment by ccoffrin** [comment]
In the engineering mode I would focus on useability first and performance second.  At the mathematical model performance is more of a concern.  Short strings should be similar in performance to Ints as Dict keys.

**Comment by pseudocubic** [comment]
My preference is for Ints personally, but we can use strings if there is a strong reason to support strings as terminal ids. I'm not really sure that I see one, and having ints makes matrix indexation easier in my mind

**Comment by pseudocubic** [comment]
we will change type to `Vector{Int} || Vector{String}` but not `Vector{Union{Int,String}}`
