### ISSUE TITLE
Which takes presidence, cm_ub or sm_ub if both are specified?

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#38]
to answer this question, I recomend that there is no precedence among these they are independent pieces of data.  It is the job of the optimization and data processing to capture one, both or determine if one is redundant in light of the other.

**Comment by sanderclaeys** [comment]
I agree.

(the current implementation automatically determines the tightest implied bound for both current and power, if also voltage bounds are specified, through the data processing methods in `data.jl`)
