### ISSUE TITLE
Tranformer Electrical Parameters

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#40]
I am not seeing where the transformer parameters come from, is it a transformer code or directly inside the object?  Fields seem to be missing in the AL2W case.

**Comment by pseudocubic** [comment]
The al2w case is a special case of transformer, in that it uses regular transformer fields, with some exceptions. This could be made more clear.

**Comment by ccoffrin** [comment]
Still, in the more general transformer model, does a "transformer code" appear in there?  I do not recall seeing it.

**Comment by pseudocubic** [comment]
that's an oversight, good catch, we will make sure to add xfmrcode

**Comment by pseudocubic** [comment]
will add `xfmrcode`, and update clarity of explanation of AL2W
