### ISSUE TITLE
Switch Control

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#41]
Is there a way to specify if a switch is controllable or not?  One possibility is to use the `dispatchable` approach for this.

**Comment by pseudocubic** [comment]
Right now, no, though I was looking at using enum. Dispatchable could be a good candidate though and it will match with conventions across infrastructure models better.

**Comment by sanderclaeys** [comment]
I am in favor of having two fields, one to indicate the state and another to indicate whether the state can be changed (`dispatchable` is a good candidate).

**Comment by pseudocubic** [comment]
will add `dispatchable`, which will take enum FIXED or FREE

**Comment by ccoffrin** [comment]
I would consider `YES`\`NO` for this. `FREE` is not super intuitive to me, out of context on might think, dispatching costs money or is free.

**Comment by sanderclaeys** [comment]
I updated the enum values. 

However, I am wondering whether `dispatchable` is the best term for components such as loads, when it actually means `shedable`. Loads are often considered in the context of flexible demand, and dispatchable for me implies a continuous adjustment range.
