### ISSUE TITLE
Specialization of shunt_capacitor and shunt_reactor

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#42]
Can these really get away without a `gs` value?  It seems to assume a level of data quality that have I not often seen.

**Comment by sanderclaeys** [comment]
@pseudocubic 
The only reason these are not collapsed to `shunt`, is to mirror the source component from OpenDSS more closely, where you can only enter a `b` value.

**Comment by bluejuniper** [comment]
Shunt capacitors will have discharge resistors across the terminals so `gs` in Real Life will not be negligible

**Comment by ccoffrin** [comment]
I would say it is fine for format to be more general than OpenDSS, as long as it can natively support all of the parts of OpenDSS that we want to support.

**Comment by pseudocubic** [comment]
@bluejuniper is it worth keeping track of shunt_capacitors, vs shunt reactors, vs generic shunts? is there extra information that we will ever need to add to shunt_capacitor and not to shunt_reactor for example?

**Comment by bluejuniper** [comment]
The transient behavior of shunt capacitors and reactors is different. Shunt capacitors can cause overvoltages when they are connected, shunt reactors can cause overvoltages when they are disconnected. 

Also, have you considered how to model static var compensators? There are a number of different topologies, but mostly they behave as (and sometimes really are) inverters with no power source connected to the dc-link.
