### ISSUE TITLE
Generator control_mode

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#43]
Are we mixing power flow semantics with control modes here?  For example is fixed P/Q really possible?  I would have expected values like PV and droop.

**Comment by pseudocubic** [comment]
I might be mixing them up. Is `model` the typical term to define e.g. PQ, PV, and `control_mode` more for e.g. droop and isochronous?

**Comment by ccoffrin** [comment]
Control mode in my mind has to do with a setting of a local control algorithm.  "bus_type" is used in transmission systems to refer to how a bus will be treated in a Power Flow study.  This is not really a component parameter, but more of data that is required for a specific type of solution method.  I would be inclined to omit "bus_type" from the data model and compute it as part of the model building process.

**Comment by pseudocubic** [comment]
I see, so in the the workflow where we parse a dss file, you are suggesting that we would set properties on the generator's bus based on the `model` that dss specifies as parse-time, and when people build their own model they set the properties on the bus based on the injection model they want from the generator?

Do you have suggestions for any `control_mode` other than droop and isochronous at this time?

**Comment by ccoffrin** [comment]
It's not really my specialty but something like `PV` makes sense, but it might be equivalent to `droop`.

**Comment by pseudocubic** [comment]
proposal is to change `control_mode` to only support enum `DROOP` `ISOCHRONOUS`, and if `vg` is specified we will assume PV generator
