### ISSUE TITLE
Control Mode in other components

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#44]
Should Solar, Wind and Storage also have control modes similar to generators?

**Comment by pseudocubic** [comment]
They ultimately probably should, I just didn’t have potential values for them yet, in case there would be different options than generators, so we were pushing the definition of that field until we needed it

**Comment by sanderclaeys** [comment]
Should we perhaps remove them from the initial spec then, and put them in a separate document until then?

**Comment by ccoffrin** [comment]
It would be helpful for several projects to have Solar and Storage in the first supported version of this.

**Comment by pseudocubic** [comment]
we definitely need those components, but I think we can push the discussion on what control modes we need to 0.9.1, we'll gauge its priority based on what people need it for
