### ISSUE TITLE
Non-Symetrical Angles at a Voltage Source

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#45]
might you want to model some non-symetrical voltage angles?  This seems more consistent with providing a vector of `vm` and would allow you to more accurately model a boundary condition.

**Comment by pseudocubic** [comment]
@sanderclaeys @frederikgeth

**Comment by sanderclaeys** [comment]
Yes, definitely. I intended `va` as such, but this must have changed in some iteration and I missed it.
