### ISSUE TITLE
Curves Seem Too Generic

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#46]
This does not appear to be fully defined.  Do these apply to specific types of components?  If so, maybe embed them inside that component?  A similar situation are generator cost functions that can model very similar curves.

**Comment by pseudocubic** [comment]
For sure they are needed to support solar components if we want to allow users to provide irradiation values in the future. You have a point about them potentially not being useful for a lot of different components though, I will research whether they are needed on other things we plan to add in the future, and if not, your suggest to add them directly to the component is probably best.

**Comment by ccoffrin** [comment]
Agreed.

The name I am used to seeing this type of data called is piecewise linear functions.  It is quite popular in the more advanced features of power systems tools.  I generally do not like such encodings becouse they are extremely general (can be constant, linear, convex, non-convex,...).  Lots of data cleaning is required (e.g. what if the linear segments do not cover the full operating range of the component?).  Making a tool that supports the most general case is very challenging.

Usually I see these functions being used to model what looks like a smooth nonlinear function.  In that case a 1D polynomial would be a much more natural representation.

**Comment by pseudocubic** [comment]
Curves in this context are merely linear interpolation between points given by x and y vectors. They only apply to two things right now, `fuse_curve` and `minimum_melting_curve`, and are slated to be used for p-t curves for `solar` in the future. We will remove the `curve` object and move this information directly to the components themselves
