### ISSUE TITLE
Time Series in Codes

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#49]
The semantics of supporting time series in line codes and the components may be quite hard to understand.  Is it possible to only support one or the other?

**Comment by pseudocubic** [comment]
It might be a better idea to pare down the initially supported time series to the more common cases, generators, storage, loads, and solar. My potential use case for supporting them on things like lines was that i thought resistances could vary during the day based on weather or something, but I don’t think this is a common use case that’s need in the immediate term. Thoughts?

**Comment by sanderclaeys** [comment]
I would limit the initial spec to what we actually plan to support in the implementation from the start. So that being said, for me this feature is not a priority. This is easy to add later on as the use case arises, and wouldn't be break the spec either as it is a straight-forward extension.

**Comment by pseudocubic** [comment]
Will pare down time_series to not include any edge objects at this time. In near term, support for switches should be added so that switch state can be altered as a function of time
