### ISSUE TITLE
Time Series Time Values

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#50]
There needs to be a way to correctly line up time series that do not have consistent starting times and are not quantized.  One simple fix would be to add a required "start_time" field that at a UTC encoded string to identify the offset of the hours list.

**Comment by pseudocubic** [comment]
Need a longer discussion about how to line up time series that don't match and offsets, etc. Will only support time series that match in initial release, and non-matching time series can be handled in a future release
