### ISSUE TITLE
Some Naming Conventions

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#51]
I think these could be improved,
- `set_vbase` `set_sbase` in settings
- use of `connections`key in components and `terminals` key in buses, seems confusing.
- `vnom`/`snom` check consistency with rest of spec.  Maybe should be `vm_nom` and `sm_nom`?  For example see `tm_nom`

**Comment by pseudocubic** [comment]
Accept change `vm_nom`, `sm_nom` to match `tm_nom`

To us, connections implies something a specific object is connecting to, whereas terminals on buses are terminals which are active on a bus, and can be connected to by many components, the semantics are slightly different between the two and we feel this justifies slightly different terminologies

will change to `vbase_default` and `sbase_default`, @sanderclaeys will expound on purposes of these, and we will update explanation in the model documentation
