### ISSUE TITLE
rx value in transformers

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#52]
It seems odd to me that transforms have `rs` and `xsc` and not `xs` and `rsc`.  A hard learned lesson for me was that it is almost always best to specify electrical values should in a complex form, even if that means some parts are zero most of the time.

**Comment by sanderclaeys** [comment]
I agree for `xsc/rsc`, though I would make an exception for `rs`. The winding resistance `rs` is measured by passing a DC-current from one phase to another, so inductance doesn't make much sense here. I will rename it to `rw` though, with `w` for winding.
