### ISSUE TITLE
Time Series Specification in Components

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#53]
The subsets of keys that are supported seem arbitrary to me.  For example on a bus, why can I put time series on `vm_lb` and not `vm_pair_lb`, or any other value?  In general, can time series be applied to any component value?

I would also like to propose an alternative encoding.  In stead of,
```
{
...
"vm_time_series" : Any,
"va_time_series" : Any,
...
}
```
How about,
```
{
...
"time_series" : {
  "vm": Any,
  "va": Any,
  }
...
}
```
For all key/value pairs in "time_series", the semantics is look up the time series information based on the "value" and apply that series to the "key" in the parent Dict.  The key "time_series" is forbidden inside of "time_series".

**Comment by pseudocubic** [comment]
Hmm, we were considering something like this for controls when we get around to adding them, that is probably a more elegant way to define time series

**Comment by pseudocubic** [comment]
we will update to use @ccoffrin's suggestion of having a `"time_series"` dictionary instead of components where the user can specify `time_series` objects for each parameter
